trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  screenshotPath: '$(Build.SourcesDirectory)/screenshot.png' # Update this to the path where the screenshot is saved

steps:
- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/cloning/*.png'
    targetFolder: '$(Build.ArtifactStagingDirectory)/FailedTest'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/FailedTest'
    artifactName: 'FailedTest'
  displayName: 'Publish failed test screenshots'
- task: CopyFiles@2
  inputs:
    contents: '**/*.png'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Screenshots'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Screenshots'
    artifactName: 'Screenshots'
  displayName: 'Publish failed test screenshots'  
        
- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/**/*.png'
    targetFolder: '$(Build.ArtifactStagingDirectory)/FailedTestScreenshots'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/FailedTestScreenshots'
    artifactName: 'FailedTestScreenshots'
  displayName: 'Publish failed test screenshots'
  
# pool:
#   vmImage: 'windows-latest'

# trigger: none

# stages:
#   - stage: Build
#     jobs:
#       - job: Build
#         steps:
#           - task: UseDotNet@2
#             inputs:
#               packageType: 'sdk'
#               version: '6.0.x'

#           - task: NuGetToolInstaller@1

#           - task: NuGetCommand@2
#             inputs:
#               restoreSolution: 'AzureDevOpsUnitTestsExample.sln'

#           - task: DotNetCoreCLI@2
#             inputs:
#               command: 'build'
#               projects: '**/*.csproj'
#               arguments: '--configuration Debug'

#   - stage: Test
#     jobs:
#       - job: Test
#         steps:
#           - task: DotNetCoreCLI@2
#             continueOnError: true
#             inputs:
#               command: 'test'
#               projects: '**/*Test*/*.csproj'
#               arguments: '--configuration Debug --logger:trx'

#           - task: PublishTestResults@2
#             inputs:
#               testResultsFormat: 'VSTest'
#               testResultsFiles: '**/TestResults/*.trx'
#               searchFolder: '$(System.DefaultWorkingDirectory)'

#           - task: CopyFiles@2
#             inputs:
#               SourceFolder: '$(System.DefaultWorkingDirectory)/TestProject1/TestResults'
#               Contents: '**/Screenshots/*'
#               TargetFolder: '$(Build.ArtifactStagingDirectory)/Screenshots'

#           - task: PublishBuildArtifacts@1
#             inputs:
#               pathtoPublish: '$(Build.ArtifactStagingDirectory)/Screenshots'
#               artifactName: 'Screenshots'
